start-at-login = true

#exec-on-workspace-change = ['/bin/bash', '-c',
#    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
#]

gaps.outer.top = 0
gaps.outer.right = 0

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
alt-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'

[workspace-to-monitor-force-assignment]
1 = '2'
2 = '2'
3 = '1'
4 = '1'
5 = 'main'
6 = ['secondary', 'main']
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['secondary', 'main']

[on-window-detected]
[[on-window-detected.rules]]
app-id = 'org.alacritty'
move-to-workspace = '1'
focus-after-move = true

[[on-window-detected.rules]]
app-id = 'com.brave.Browser'
move-to-workspace = '2'
focus-after-move = true

[[on-window-detected.rules]]
app-id = 'com.tinyspeck.slackmacgap'
move-to-workspace = '3'
focus-after-move = true

[[on-window-detected.rules]]
app-id = 'com.microsoft.teams2'
move-to-workspace = '4'
focus-after-move = true
